export {default as twitter} from './twitter.png'
export {default as pocket} from './pocket.png'
export {default as chrome} from './chrome.png'
export {default as slack} from './slack.png'
export {default as rightArrow} from './right.png'